import re

# Common regex patterns for sensitive keys and tokens
SECRET_PATTERNS = [
    r"(?:api[_-]?key|apikey)['\"].*?['\"]([a-zA-Z0-9_\-]{16,})['\"]",
    r"(?:bearer|token)['\"].*?['\"]([a-zA-Z0-9_\-\.]{20,})['\"]",
    r"AKIA[0-9A-Z]{16}",  # AWS Access Key ID
    r"sk_live_[0-9a-zA-Z]{24}",  # Stripe Live Secret Key
    r"ghp_[a-zA-Z0-9]{36}",  # GitHub Personal Access Token
]

def scan_file_for_secrets(file_path):
    """Scans a target source file for leaked secrets and flags them."""
    try:
        with open(file_path, "r", encoding="utf-8", errors="ignore") as f:
            content = f.read()
            
        for pattern in SECRET_PATTERNS:
            if re.search(pattern, content, re.IGNORECASE):
                return True
    except Exception:
        pass
    return False

def generate_env_example():
    """Generates a safe .env.example template for enterprise workflows."""
    env_template = """# Auto-generated by AutoEnv Security Pre-flight
# Replace placeholders with your actual runtime configuration secrets
DATABASE_URL=postgres://user:password@localhost:5432/dbname
API_KEY=AUTOENV_SECRET_REDACTED
SECRET_KEY=AUTOENV_SECRET_REDACTED
"""
    with open(".env.example", "w") as f:
        f.write(env_template)